name: srvls
description: A simple command-line application.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  shelf_router: ^0.7.4
  shelf: ^0.7.9

dev_dependencies:
  pedantic: ^1.9.0
